### ISSUE TITLE
Volume keys are not being identified

### ISSUE THREAD

**Issue by fabianski7** [micro5k/microg-unofficial-installer#64]
I tested it on crdroid on android 13 and on havoc on a11 and in neither case was this app installed. How can I help debug this?
I am using a oneplus 6 (enchilada)

**Comment by ale5000-git** [comment]
Aurora Services isn't installed by default, but during the zip flashing you could use the live setup to enable it.

**Comment by ale5000-git** [comment]
Yes, it works perfectly in TWRP.

TWRP have an option to copy log.
Could you please flash the zip and copy the log to I can see what happens?

**Comment by ale5000-git** [comment]
The warning that I have put was too much generic, now I have improved it.
Could you please retry this this installer and then post recovery.log again?

**Comment by ale5000-git** [comment]
@fabianski7
No problem but you have flashed the v1.3.1-beta, not the one of the link.

**Comment by ale5000-git** [comment]
@fabianski7
When you have time could you please try this new test build and tell me if the situation has improved or nothing is changed and post the recovery.log again?
https://androidfilehost.com/?fid=10620683726822057810

**Comment by ale5000-git** [comment]
@fabianski7
It is a really strange issue, could you please try even this and post the log?
https://androidfilehost.com/?fid=10620683726822057832

**Comment by ale5000-git** [comment]
> [recovery (4).log](https://github.com/micro5k/microg-unofficial-installer/files/11657987/recovery.4.log)

Is the problem reduced or it is still the same?

**Comment by ale5000-git** [comment]
Sorry for the wait but the code isn't ready yet, I had encountered a strange issue that I need to fix.

**Comment by ale5000-git** [comment]
@fabianski7
Could you please try this and post the recovery.log?
https://androidfilehost.com/?fid=10620683726822061683

**Comment by ale5000-git** [comment]
@fabianski7

Hi,
it seems that the problem is in the parsing; it get the wrong key code.
Since it works on my phone maybe on your phone it emit a different sequence on key press.

Could you please do this?
- Restart the phone in the recovery
- Connect to the pc via usb
- On the pc run `adb shell`
- Inside the adb shell execute: `cat /dev/input/event3 | hexdump -v -x`
- Press volume + on the phone and transcribe the output the you get inside the shell
- Release volume + on the phone and transcribe the output the you get inside the shell
- Press volume - on the phone and transcribe the output the you get inside the shell
- Release volume - on the phone and transcribe the output the you get inside the shell

**Comment by ale5000-git** [comment]
@fabianski7

Could you please do this?
- Restart the phone in the recovery
- Connect to the pc via usb
- On the pc in the command prompt execute: `adb shell`
- Inside the adb shell execute: `cat /dev/input/event3 > /tmp/event-log.dat`
- Press and release volume + on the phone
- Close the `adb shell`
- On the pc get the saved file with: `adb pull /tmp/event-log.dat .`
- Upload the file `event-log.dat` here

**Comment by ale5000-git** [comment]
@fabianski7
The problem was that the timestamp of the input event is more bigger on your phone (probably because of the differences between 32/64-bit) and the data that I need was shifted.

It should now be fixed, could you please try this and post the recovery.log?
https://androidfilehost.com/?fid=10620683726822062571

**Comment by ale5000-git** [comment]
Very good, thanks for the testing :)
